### ISSUE TITLE
bw2 android publish seems no longer work

### ISSUE THREAD

**Issue by TongLi1992** [SoftwareDefinedBuildings/bw2android#2]
bwclient.publish's callback function return a response.
response.getReason() return : We don't support full elaboration anymore

**Comment by jhkolb** [comment]
Hmm, this sounds like there was a change in Bosswave itself rather than something that broke in the bindings. Maybe @immesys can confirm?

**Comment by jhkolb** [comment]
So, the problem is that your code is using the full chain elaboration mode, and Bosswave no longer uses this. By default, the bindings should set the elaboration mode to "partial."

Are you explicitly setting your publish requests to use the full elaboration mode? If so, you can just remove that. Don't forget to set `autoChain` as well.

If this doesn't resolve your problem, feel free to post the snippet of code you are using to construct the publish requests.

**Comment by TongLi1992** [comment]
@jhkolb 
Changing the line from 
`builder.setChainElaborationLevel(ChainElaborationLevel.FULL);`
to
`builder.setChainElaborationLevel(ChainElaborationLevel.PARTIAL);`
solved the problem!
Thanks!
